config/routes.rb
Rails.application.routes.draw do
  get "/pages/*page" => "pages#show"
  devise_for :users
  devise_scope :user do
    root 'pages#show', page: "home_user"
  end
  root "pages#show", page: "home"

  namespace :config do
    resources :steps
  end
  resources :documents
  namespace :config do
    resources :document_templates
  end
  resources :events
  resources :contacts
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/config/document_template.rb
class Config::DocumentTemplate
  include Mongoid::Document
  field :document_name, type: String
  field :document_type, type: String
end

app/models/config/step.rb
class Config::Step
  include Mongoid::Document

  field :step_position, type: Integer
  field :step_name, type: String

  default_scope { order_by(step_position: "asc") }
end

app/models/document_template.rb
class DocumentTemplate
  include Mongoid::Document
  field :document_name, type: String
  field :document_type, type: String
end

app/controllers/config/document_templates_controller.rb
class Config::DocumentTemplatesController < ApplicationController
  before_action :set_config_document_template, only: [:show, :edit, :update, :destroy]

  # GET /config/document_templates
  # GET /config/document_templates.json
  def index
    @config_document_templates = Config::DocumentTemplate.all
  end

  # GET /config/document_templates/1
  # GET /config/document_templates/1.json
  def show
  end

  # GET /config/document_templates/new
  def new
    @config_document_template = Config::DocumentTemplate.new
  end

  # GET /config/document_templates/1/edit
  def edit
  end

  # POST /config/document_templates
  # POST /config/document_templates.json
  def create
    @config_document_template = Config::DocumentTemplate.new(config_document_template_params)

    respond_to do |format|
      if @config_document_template.save
        format.html { redirect_to @config_document_template, notice: 'Document template was successfully created.' }
        format.json { render :show, status: :created, location: @config_document_template }
      else
        format.html { render :new }
        format.json { render json: @config_document_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /config/document_templates/1
  # PATCH/PUT /config/document_templates/1.json
  def update
    respond_to do |format|
      if @config_document_template.update(config_document_template_params)
        format.html { redirect_to @config_document_template, notice: 'Document template was successfully updated.' }
        format.json { render :show, status: :ok, location: @config_document_template }
      else
        format.html { render :edit }
        format.json { render json: @config_document_template.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /config/document_templates/1
  # DELETE /config/document_templates/1.json
  def destroy
    @config_document_template.destroy
    respond_to do |format|
      format.html { redirect_to config_document_templates_url, notice: 'Document template was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config_document_template
      @config_document_template = Config::DocumentTemplate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_document_template_params
      params.require(:config_document_template).permit(:document_name, :document_type)
    end
end

app/controllers/config/steps_controller.rb
class Config::StepsController < ApplicationController
  before_action :set_config_step, only: [:show, :edit, :update, :destroy]

  # GET /config/steps
  # GET /config/steps.json
  def index
    @config_steps = Config::Step.all
  end

  # GET /config/steps/1
  # GET /config/steps/1.json
  def show
  end

  # GET /config/steps/new
  def new
    @config_step = Config::Step.new
  end

  # GET /config/steps/1/edit
  def edit
  end

  # POST /config/steps
  # POST /config/steps.json
  def create
    @config_step = Config::Step.new(config_step_params)

    respond_to do |format|
      if @config_step.save
        format.html { redirect_to @config_step, notice: 'Step was successfully created.' }
        format.json { render :show, status: :created, location: @config_step }
      else
        format.html { render :new }
        format.json { render json: @config_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /config/steps/1
  # PATCH/PUT /config/steps/1.json
  def update
    respond_to do |format|
      if @config_step.update(config_step_params)
        format.html { redirect_to @config_step, notice: 'Step was successfully updated.' }
        format.json { render :show, status: :ok, location: @config_step }
      else
        format.html { render :edit }
        format.json { render json: @config_step.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /config/steps/1
  # DELETE /config/steps/1.json
  def destroy
    @config_step.destroy
    respond_to do |format|
      format.html { redirect_to config_steps_url, notice: 'Step was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_config_step
      @config_step = Config::Step.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def config_step_params
      params.require(:config_step).permit(:step_name)
    end
end

app/views/config/document_templates/_form.html.erb
<%= form_with(model: config_document_template, local: true) do |form| %>
  <% if config_document_template.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(config_document_template.errors.count, "error") %> prohibited this config_document_template from being saved:</h2>

      <ul>
      <% config_document_template.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :document_name %>
    <%= form.text_field :document_name, id: :config_document_template_document_name %>
  </div>

  <div class="field">
    <%= form.label :document_type %>
    <%= form.text_field :document_type, id: :config_document_template_document_type %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/config/document_templates/edit.html.erb
<h1>Editing Config Document Template</h1>

<%= render 'form', config_document_template: @config_document_template %>

<%= link_to 'Show', @config_document_template %> |
<%= link_to 'Back', config_document_templates_path %>

app/views/config/document_templates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Config Document Templates</h1>

<table>
  <thead>
    <tr>
      <th>Document name</th>
      <th>Document type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @config_document_templates.each do |config_document_template| %>
      <tr>
        <td><%= config_document_template.document_name %></td>
        <td><%= config_document_template.document_type %></td>
        <td><%= link_to 'Show', config_document_template %></td>
        <td><%= link_to 'Edit', edit_config_document_template_path(config_document_template) %></td>
        <td><%= link_to 'Destroy', config_document_template, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Config Document Template', new_config_document_template_path %>

app/views/config/document_templates/new.html.erb
<h1>New Config Document Template</h1>

<%= render 'form', config_document_template: @config_document_template %>

<%= link_to 'Back', config_document_templates_path %>

app/views/config/document_templates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Document name:</strong>
  <%= @config_document_template.document_name %>
</p>

<p>
  <strong>Document type:</strong>
  <%= @config_document_template.document_type %>
</p>

<%= link_to 'Edit', edit_config_document_template_path(@config_document_template) %> |
<%= link_to 'Back', config_document_templates_path %>