config/routes.rb
Rails.application.routes.draw do
  get "/pages/*page" => "pages#show"
  devise_for :users
  devise_scope :user do
    root 'pages#show', page: "home_user"
  end
  root "pages#show", page: "home"

  namespace :config do
    resources :steps
  end
  resources :documents
  namespace :config do
    resources :document_templates
  end
  resources :events
  resources :contacts
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/company.rb
class Company
  include Mongoid::Document
  field :company, type: String
  field :siret, type: String

  belongs_to :step, class_name: 'Config::Step'

  after_create :send_welcome_email

  def send_welcome_email
    CompanyMailer.welcome_email()
  end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @steps = Config::Step.all
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:company, :siret, :step_id)
    end
end

app/views/companies/_form.html.erb
<%= form_with(model: company, local: true) do |form| %>
  <% if company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :company %>
    <%= form.text_field :company, id: :company_company %>
  </div>

  <div class="field">
    <%= form.label :siret %>
    <%= form.text_field :siret, id: :company_siret %>
  </div>

  <div class="field">
    <%= form.label :step %>
    <%= form.select :step_id, Config::Step.all.collect {|s| [ s.step_name, s.id ] }, id: :company_step_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/companies/_show.html.erb
<div class="by acy adh">
  <div class="dp">
    <div class="fj">
      <div class="mu blf abk">
        <div class="na" style="background-image: url(/assets/iceland.jpg);"></div>
        <div class="mv arx">
          <a href="profile/index.html">
            <img class="blg" src="/assets/ClaireKilic.jpg">
          </a>

          <h6 class="mw">
            <a class="bjx" href="profile/index.html">Claire Kilic</a>
          </h6>

          <p class="abk">
            claire.kilic@plezi.co<br>
            06 06 06 06 06
          </p>

          <ul class="blh">
            <li class="bli">
              <a href="#userModal" class="bjx" data-toggle="modal">
                Friends
                <h6 class="aal">12M</h6>
              </a>
            </li>

            <li class="bli">
              <a href="#userModal" class="bjx" data-toggle="modal">
                Enemies
                <h6 class="aal">1</h6>
              </a>
            </li>
          </ul>
        </div>
      </div>

      <div class="mu sh sp abk">
        <div class="mv">
          <h6 class="abd">About Plezi</h6>
          <ul class="dc atd">
            <li><span class="asz h awk abc"></span>Went to <a href="#">Oh, Canada</a>
            </li><li><span class="asz h biz abc"></span>Became friends with <a href="#">Obama</a>
            </li><li><span class="asz h bax abc"></span>Worked at <a href="#">Github</a>
            </li><li><span class="asz h bbn abc"></span>Lives in <a href="#">San Francisco, CA</a>
            </li><li><span class="asz h bcw abc"></span>From <a href="#">Seattle, WA</a>
          </li></ul>
        </div>
      </div>

       <div class="mu sh sp abk">
        <div class="mv">
          <h6 class="abd">Photos <small>· <a href="#">Edit</a></small></h6>
          <div data-grid="images" data-target-height="150"><div style="margin-bottom: 10px; margin-right: 10px; display: inline-block; vertical-align: bottom;">
              <img data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_5.jpg" style="width: 114px; height: 115px;">
            </div><div style="margin-bottom: 10px; margin-right: 0px; display: inline-block; vertical-align: bottom;">
              <img data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_6.jpg" style="width: 114px; height: 115px;">
            </div><div style="margin-bottom: 10px; margin-right: 10px; display: inline-block; vertical-align: bottom;">
              <img data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_7.jpg" style="width: 114px; height: 115px;">
            </div><div style="margin-bottom: 10px; margin-right: 0px; display: inline-block; vertical-align: bottom;">
              <img data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_8.jpg" style="width: 114px; height: 115px;">
            </div><div style="margin-bottom: 10px; margin-right: 10px; display: inline-block; vertical-align: bottom;">
              <img data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_9.jpg" style="width: 114px; height: 115px;">
            </div><div style="margin-bottom: 10px; margin-right: 0px; display: inline-block; vertical-align: bottom;">
              <img data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_10.jpg" style="width: 114px; height: 115px;">
            </div></div>
        </div>
      </div>
    </div>

    <div class="fm">

      <ul class="ca bkt bku abk">

        <li class="oq b acx">
          <div class="input-group">
            <input type="text" class="form-control" placeholder="Message">
            <div class="jq">
              <button type="button" class="cg kt uo">
                <span class="h awl"></span>
              </button>
            </div>
          </div>
        </li>

        <li class="oq b acx">
          <img class="bkp ru uk abc" src="assets/img/avatar-dhg.png">
          <div class="or">
            <div class="bky">
              <small class="zc asz">4 min</small>
              <h6>Dave Gamache</h6>
            </div>

            <p>
              Aenean lacinia bibendum nulla sed consectetur. Vestibulum id ligula porta felis euismod semper. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.
            </p>

            <div class="bkv" data-grid="images"><div style="display: inline-block; margin-bottom: 10px; margin-right: 10px; vertical-align: bottom;">
                <img data-action="zoom" data-width="1050" data-height="700" src="assets/img/unsplash_1.jpg" style="width: 273px; height: 182px;" class="">
              </div><div style="display: inline-block; margin-bottom: 10px; margin-right: 0px; vertical-align: bottom;">
                <img data-action="zoom" data-width="640" data-height="640" src="assets/img/instagram_1.jpg" style="width: 182px; height: 182px;">
              </div><div style="display: inline-block; margin-bottom: 10px; margin-right: 10px; vertical-align: bottom;">
                <img data-action="zoom" data-width="640" data-height="640" src="assets/img/instagram_13.jpg" style="width: 181px; height: 182px;">
              </div><div style="display: inline-block; margin-bottom: 10px; margin-right: 0px; vertical-align: bottom;">
                <img data-action="zoom" data-width="1048" data-height="700" src="assets/img/unsplash_2.jpg" style="width: 274px; height: 182px;">
              </div></div>

            <ul class="bkt aaw">
              <li class="oq abd">
                <img class="bkp ru uk abc" src="assets/img/avatar-fat.jpg">
                <div class="or">
                  <strong>Jacon Thornton: </strong>
                  Donec id elit non mi porta gravida at eget metus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Sed posuere consectetur est at lobortis.
                </div>
              </li>
              <li class="oq">
                <img class="bkp ru uk abc" src="assets/img/avatar-mdo.png">
                <div class="or">
                  <strong>Mark Otto: </strong>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus.
                </div>
              </li>
            </ul>
          </div>
        </li>

        <li class="oq b acx">
          <img class="bkp ru uk abc" src="assets/img/avatar-fat.jpg">
          <div class="or">
            <div class="bla">
              <div class="bky">
                <small class="zc asz">12 min</small>
                <h6>Jacob Thornton</h6>
              </div>
              <p>
                Donec id elit non mi porta gravida at eget metus. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Morbi leo risus, porta ac consectetur ac, vestibulum at eros. Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              </p>
            </div>
          </div>
        </li>

        <li class="oq b acx">
          <img class="bkp ru uk abc" src="assets/img/avatar-mdo.png">
          <div class="or">
            <div class="bky">
              <small class="zc asz">34 min</small>
              <h6>Mark Otto</h6>
            </div>

            <p>
              Donec ullamcorper nulla non metus auctor fringilla. Vestibulum id ligula porta felis euismod semper. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.
            </p>

            <div class="bkv" data-grid="images"><img style="display: inline-block; width: 466px; height: 451px; margin-bottom: 10px; margin-right: 0px; vertical-align: bottom;" data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_3.jpg"></div>

            <ul class="bkt">
              <li class="oq">
                <img class="bkp ru uk abc" src="assets/img/avatar-dhg.png">
                <div class="or">
                  <strong>Dave Gamache: </strong>
                  Donec id elit non mi porta gravida at eget metus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Donec ullamcorper nulla non metus auctor fringilla. Praesent commodo cursus magna, vel scelerisque nisl consectetur et. Sed posuere consectetur est at lobortis.
                </div>
              </li>
            </ul>
          </div>
        </li>
      </ul>
    </div>
    <div class="fj">
      <div class="alert oj alert-dismissible ro sp" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
        <a class="oe" href="profile/index.html">Visit your profile!</a> Check your self, you aren't looking well.
      </div>

      <div class="mu abk ro sp">
        <div class="mv">
          <h6 class="abd">Sponsored</h6>
          <div data-grid="images" data-target-height="150"><img class="bkp" data-width="640" data-height="640" data-action="zoom" src="assets/img/instagram_2.jpg" style="width: 239px; height: 225px; margin-bottom: 10px; margin-right: 0px; display: inline-block; vertical-align: bottom;"></div>
          <p><strong>It might be time to visit Iceland.</strong> Iceland is so chill, and everything looks cool here. Also, we heard the people are pretty nice. What are you waiting for?</p>
          <button class="cg la ll">Buy a ticket</button>
        </div>
      </div>

      <div class="mu abk ro sp">
        <div class="mv">
        <h6 class="abd">Likes <small>· <a href="#">View All</a></small></h6>
        <ul class="bkt bku">
          <li class="oq aaw">
            <img class="bkp ru uk abc" src="assets/img/avatar-fat.jpg">
            <div class="or">
              <strong>Jacob Thornton</strong> @fat
              <div class="bkx">
                <button class="cg la ll">
                  <span class="h auf"></span> Follow</button>
              </div>
            </div>
          </li>
           <li class="oq">
            <a class="blq" href="#">
              <img class="bkp ru uk abc" src="assets/img/avatar-mdo.png">
            </a>
            <div class="or">
              <strong>Mark Otto</strong> @mdo
              <div class="bkx">
                <button class="cg la ll">
                  <span class="h auf"></span> Follow</button>
              </div>
            </div>
          </li>
        </ul>
        </div>
        <div class="nb">
          Dave really likes these nerds, no one knows why though.
        </div>
      </div>

      <div class="mu blj">
        <div class="mv">
          © 2018 Bootstrap
          <a href="#">About</a>
          <a href="#">Help</a>
          <a href="#">Terms</a>
          <a href="#">Privacy</a>
          <a href="#">Cookies</a>
          <a href="#">Ads </a>
          <a href="#">Info</a>
          <a href="#">Brand</a>
          <a href="#">Blog</a>
          <a href="#">Status</a>
          <a href="#">Apps</a>
          <a href="#">Jobs</a>
          <a href="#">Advertise</a>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Companies</h1>

<table>
  <thead>
    <tr>
      <th>Company</th>
      <th>Siret</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= company.company %></td>
        <td><%= company.siret %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form', company: @company %>

<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @company.company %></h1>

<%= render partial: "show" %>

<h4>My sales contact at Plezi:</h4>
Claire Kilic<br>
claire.kilic@plezi.co<br>
06 06 06 06 06


<h4>My process</h4>
<% @steps.each do |step| %>
  <% if @company.step_id == step.id %>
    <b><%= step.step_name %></b>
  <% else %>
    <%= step.step_name %>
  <% end %>
<% end %>

<h4>My documents</h4>
<%= link_to "Add a document", new_document_url %>

<h4>Next steps</h4>
<%= link_to "Add a step", new_document_url %>

<div class="">
  <%= link_to 'Edit', edit_company_path(@company) %> |
  <%= link_to 'Back', companies_path %>
</div>